if (!self.define) {
  let s,
    l = {};
  const e = (e, n) => (
    (e = new URL(e + ".js", n).href),
    l[e] ||
      new Promise((l) => {
        if ("document" in self) {
          const s = document.createElement("script");
          (s.src = e), (s.onload = l), document.head.appendChild(s);
        } else (s = e), importScripts(e), l();
      }).then(() => {
        let s = l[e];
        if (!s) throw new Error(`Module ${e} didn’t register its module`);
        return s;
      })
  );
  self.define = (n, i) => {
    const r =
      s ||
      ("document" in self ? document.currentScript.src : "") ||
      location.href;
    if (l[r]) return;
    let u = {};
    const t = (s) => e(s, r),
      o = { module: { uri: r }, exports: u, require: t };
    l[r] = Promise.all(n.map((s) => o[s] || t(s))).then((s) => (i(...s), u));
  };
}
define(["./workbox-3e8df8c8"], function (s) {
  "use strict";
  self.skipWaiting(),
    s.clientsClaim(),
    s.precacheAndRoute(
      [
        { url: "assets/_baseClone-DV5ysvAy.js", revision: null },
        { url: "assets/_baseEach-INTXt94m.js", revision: null },
        { url: "assets/_baseSlice-F8doVSIJ.js", revision: null },
        { url: "assets/_getTag-BBZl3NB0.js", revision: null },
        { url: "assets/_Map-Dn69b_0d.js", revision: null },
        { url: "assets/_MapCache-Dd7nzhZT.js", revision: null },
        { url: "assets/_Uint8Array-CDIfl2Mg.js", revision: null },
        { url: "assets/account-details-B-Y5yX5T.js", revision: null },
        { url: "assets/AccountLayoutPage-B91JEHa2.js", revision: null },
        { url: "assets/AccountLayoutPage-Bc8tBAoE.css", revision: null },
        { url: "assets/accounts-CTdEXpRp.js", revision: null },
        { url: "assets/Action-Chaeft7b.js", revision: null },
        { url: "assets/ActivateVaultPage-C9IgyUx3.js", revision: null },
        { url: "assets/ActivateVaultPage-CP55tMrn.css", revision: null },
        { url: "assets/addressValid-Buha1cAs.js", revision: null },
        { url: "assets/aes-Aa4gZgfZ.js", revision: null },
        { url: "assets/Alert-D9otgbzb.js", revision: null },
        { url: "assets/api-key-type-Bqe2ojbe.js", revision: null },
        {
          url: "assets/authenticatedLayoutContainer-D7vnPwpX.js",
          revision: null,
        },
        { url: "assets/balance-C_hol84O.js", revision: null },
        { url: "assets/BankDetails-DnrRgnxb.js", revision: null },
        { url: "assets/BankInformation-DCMXwYv_.js", revision: null },
        { url: "assets/Basic-C8TpTkuW.js", revision: null },
        { url: "assets/bootstrap-4wHWiSPL.js", revision: null },
        { url: "assets/bootstrap-CkweRzzS.css", revision: null },
        { url: "assets/BubbleTab-BNonz68w.js", revision: null },
        { url: "assets/CancelTransaction-Co47wp7J.js", revision: null },
        { url: "assets/capitalize-Crm3kySE.js", revision: null },
        { url: "assets/Chart--asC7R1O.js", revision: null },
        { url: "assets/chart-VlffLmI0.js", revision: null },
        { url: "assets/Checkbox-azwF4S2Y.js", revision: null },
        { url: "assets/Chip-BmP1UBlr.js", revision: null },
        { url: "assets/Chip-h9Fj1cSa.js", revision: null },
        { url: "assets/cloneDeep-B_n4wiWO.js", revision: null },
        { url: "assets/Collapse-UbjukSi0.js", revision: null },
        { url: "assets/ConnectionSettings-BqR6tQKY.js", revision: null },
        { url: "assets/CopyButton-B2DA-KPK.js", revision: null },
        { url: "assets/core-B6Z5XPwX.js", revision: null },
        { url: "assets/countries-C8rbApaY.js", revision: null },
        { url: "assets/CountryDropdown-hBxUUbI_.js", revision: null },
        { url: "assets/createChainedFunction-BFzlhUJR.js", revision: null },
        { url: "assets/createPopper-DLtJTqii.js", revision: null },
        { url: "assets/currencies-CvQ0yLY8.js", revision: null },
        { url: "assets/currency-boundaries-C8D7iSfd.js", revision: null },
        { url: "assets/CurrencyButton-9OA8qjAn.js", revision: null },
        { url: "assets/currencyFormatter-DqHkUfNj.js", revision: null },
        { url: "assets/CurrencyIcon-BSh20PSx.js", revision: null },
        { url: "assets/CurrencyLabel-DGg5vM54.js", revision: null },
        { url: "assets/DashboardContainer-eZk5PFq1.js", revision: null },
        { url: "assets/defineProperty-w7AU6ifp.js", revision: null },
        { url: "assets/depth.listener-Bb9oU3qt.js", revision: null },
        { url: "assets/DepthChart-BQFC0nUO.js", revision: null },
        { url: "assets/DialogActions-CR6pyUZM.js", revision: null },
        { url: "assets/DialogContent-A833hUPt.js", revision: null },
        { url: "assets/Divider-DtXA8bzM.js", revision: null },
        { url: "assets/dividerClasses-CKrR6pKE.js", revision: null },
        { url: "assets/Dropdown-B-BoUpC5.js", revision: null },
        { url: "assets/DropdownChipBase-Tvm1Fi1i.js", revision: null },
        { url: "assets/EditableText-CNK2xawk.js", revision: null },
        { url: "assets/ElementChildren-CWFdP5Iy.js", revision: null },
        { url: "assets/enc-utf8-esWO36bO.js", revision: null },
        { url: "assets/EnterMobileNumber-YMSOc5-K.js", revision: null },
        { url: "assets/Error-l5Kb-HA5.js", revision: null },
        { url: "assets/executed-orders.listener-GkgxCqGH.js", revision: null },
        { url: "assets/ExternalLayout-DSjDsG7U.js", revision: null },
        { url: "assets/feature-flag-CBj2T29d.js", revision: null },
        { url: "assets/Fees-D9d3im3Y.js", revision: null },
        { url: "assets/fiat-currencies-4YJiRIqJ.js", revision: null },
        { url: "assets/FilterProvider-Do3DlFTi.js", revision: null },
        { url: "assets/FinishCorporateKyc-C6XfFSMq.js", revision: null },
        { url: "assets/FundTransactionComponent-CbG3uNlv.css", revision: null },
        { url: "assets/FundTransactionComponent-CBwhRoAi.js", revision: null },
        { url: "assets/get-ByMDa3Ut.js", revision: null },
        { url: "assets/getCurrencySymbol-U33HH9zA.js", revision: null },
        { url: "assets/GoogleSignIn-FrW9XI9u.js", revision: null },
        { url: "assets/guestLayoutContainer-D4YVXXO0.js", revision: null },
        { url: "assets/helpers-BxXgrS-G.js", revision: null },
        { url: "assets/helpers-D0lXFcyB.js", revision: null },
        { url: "assets/HistorySection-BSjGoECs.css", revision: null },
        { url: "assets/HistorySection-EsCYJY4f.js", revision: null },
        { url: "assets/holders-BF6fZGx6.js", revision: null },
        { url: "assets/holders-DAaKEgeb.js", revision: null },
        { url: "assets/icon-names-CIWAZ9HS.js", revision: null },
        { url: "assets/icon-names-vxPMkv-6.css", revision: null },
        { url: "assets/IconButton-ClDlR7xP.js", revision: null },
        { url: "assets/image-1Zardcpj.js", revision: null },
        { url: "assets/ImportAccount-BY3hP9oJ.js", revision: null },
        { url: "assets/ImportPassphrase-04pg6yWy.js", revision: null },
        { url: "assets/index-_0m3-Fqh.js", revision: null },
        { url: "assets/index-5u7DaF_o.js", revision: null },
        { url: "assets/index-6vxM0M4a.js", revision: null },
        { url: "assets/index-AG96wckJ.js", revision: null },
        { url: "assets/index-B1IYvx0M.js", revision: null },
        { url: "assets/index-B2skL3Es.js", revision: null },
        { url: "assets/index-Ba66B7JA.js", revision: null },
        { url: "assets/index-BBKt8-YL.js", revision: null },
        { url: "assets/index-BbOSXMnP.js", revision: null },
        { url: "assets/index-BdZiPhrX.js", revision: null },
        { url: "assets/index-BgbNI1V5.js", revision: null },
        { url: "assets/index-BgzksJaa.js", revision: null },
        { url: "assets/index-Bi0RlM2G.js", revision: null },
        { url: "assets/index-BKw26fas.js", revision: null },
        { url: "assets/index-BLRu6zkC.js", revision: null },
        { url: "assets/index-BnEA88CX.js", revision: null },
        { url: "assets/index-Bo_9n-PG.js", revision: null },
        { url: "assets/index-BPrqYk5V.js", revision: null },
        { url: "assets/index-BQE79upB.js", revision: null },
        { url: "assets/index-BrAxQXmF.js", revision: null },
        { url: "assets/index-BUNUpumB.js", revision: null },
        { url: "assets/index-BuZa6cAU.js", revision: null },
        { url: "assets/index-BxuYTAaU.js", revision: null },
        { url: "assets/index-C2gnoIG6.js", revision: null },
        { url: "assets/index-C3oNsjFP.js", revision: null },
        { url: "assets/index-C4mvAiZ8.js", revision: null },
        { url: "assets/index-C6Lhtzvs.js", revision: null },
        { url: "assets/index-C6vTJKZH.js", revision: null },
        { url: "assets/index-C7glG_Ry.js", revision: null },
        { url: "assets/index-CaWJK1Jr.js", revision: null },
        { url: "assets/index-CBx3iaq5.js", revision: null },
        { url: "assets/index-CcM7Y7xD.css", revision: null },
        { url: "assets/index-CenKVK_5.js", revision: null },
        { url: "assets/index-Chya3hTY.js", revision: null },
        { url: "assets/index-CIGiuta7.js", revision: null },
        { url: "assets/index-ClyT1Ep1.js", revision: null },
        { url: "assets/index-CMrxAQzc.js", revision: null },
        { url: "assets/index-CONwkJdM.js", revision: null },
        { url: "assets/index-CRD6nWau.js", revision: null },
        { url: "assets/index-CsAWqBrZ.js", revision: null },
        { url: "assets/index-CVcrpNYJ.css", revision: null },
        { url: "assets/index-CVGWP4XK.js", revision: null },
        { url: "assets/index-CW25_mQq.js", revision: null },
        { url: "assets/index-CXHVafB5.js", revision: null },
        { url: "assets/index-CxjVi7H7.css", revision: null },
        { url: "assets/index-Cz43WgLj.js", revision: null },
        { url: "assets/index-D-VgVBE8.js", revision: null },
        { url: "assets/index-D04vYMJd.css", revision: null },
        { url: "assets/index-D05Ck5uX.js", revision: null },
        { url: "assets/index-D1ts1xtl.js", revision: null },
        { url: "assets/index-D26JJz9S.js", revision: null },
        { url: "assets/index-D2a6lNk9.js", revision: null },
        { url: "assets/index-D4hGd7fZ.js", revision: null },
        { url: "assets/index-D8Aj9pZI.js", revision: null },
        { url: "assets/index-D9Ksp2Tu.js", revision: null },
        { url: "assets/index-DamApG0r.js", revision: null },
        { url: "assets/index-DAUdMT1B.js", revision: null },
        { url: "assets/index-DC8Hqorr.js", revision: null },
        { url: "assets/index-DcgKCdml.js", revision: null },
        { url: "assets/index-DcvGW77o.js", revision: null },
        { url: "assets/index-DENdcTLt.js", revision: null },
        { url: "assets/index-DeSxTRGL.js", revision: null },
        { url: "assets/index-DFdZF_Yd.js", revision: null },
        { url: "assets/index-DgigA2fk.js", revision: null },
        { url: "assets/index-DgpVYdy4.js", revision: null },
        { url: "assets/index-DGwmAgCN.js", revision: null },
        { url: "assets/index-dgZWCLOJ.js", revision: null },
        { url: "assets/index-DHPIXLXG.js", revision: null },
        { url: "assets/index-DIAYbZYa.js", revision: null },
        { url: "assets/index-DKydy_Oh.js", revision: null },
        { url: "assets/index-DMBgV4GW.js", revision: null },
        { url: "assets/index-Do1i7yHT.js", revision: null },
        { url: "assets/index-DQUs1ZHf.js", revision: null },
        { url: "assets/index-DTOD75sv.js", revision: null },
        { url: "assets/index-DWKsSpgP.js", revision: null },
        { url: "assets/index-DYNLSiy8.js", revision: null },
        { url: "assets/index-IFRsO8-k.js", revision: null },
        { url: "assets/index-iGSc46GB.js", revision: null },
        { url: "assets/index-iIJOEUAf.js", revision: null },
        { url: "assets/index-iorX_LRX.js", revision: null },
        { url: "assets/index-iSZ3wOAz.js", revision: null },
        { url: "assets/index-J1GP0RDZ.js", revision: null },
        { url: "assets/index-koMml2oj.js", revision: null },
        { url: "assets/index-lYy8_FnI.js", revision: null },
        { url: "assets/index-muQS-9Gf.js", revision: null },
        { url: "assets/index-p4g-JDlh.js", revision: null },
        { url: "assets/index-PlqyMyPw.js", revision: null },
        { url: "assets/index-R3jGvD4E.js", revision: null },
        { url: "assets/index-Rs5enP9N.js", revision: null },
        { url: "assets/index-Sia8Y9vT.js", revision: null },
        { url: "assets/index-SlUbjU9R.js", revision: null },
        { url: "assets/index-VOoRVzdn.js", revision: null },
        { url: "assets/index-WtEfj628.js", revision: null },
        { url: "assets/index-z3BbPMFU.js", revision: null },
        { url: "assets/index-ZbKl_FBz.js", revision: null },
        { url: "assets/index.es-B63JM6fg.js", revision: null },
        { url: "assets/index.esm-B2HhHynd.js", revision: null },
        { url: "assets/index.esm-h9f6KZvT.js", revision: null },
        { url: "assets/InitialsAvatar-DPbVU1XN.js", revision: null },
        { url: "assets/Input-U7WLNE8T.js", revision: null },
        { url: "assets/InputField-DVHiyQx8.js", revision: null },
        { url: "assets/InputStatus-DpYcmRe_.js", revision: null },
        { url: "assets/isArray-Dxzbedgu.js", revision: null },
        { url: "assets/isObject-C3e4t58V.js", revision: null },
        { url: "assets/isObjectLike-BR2ybR99.js", revision: null },
        { url: "assets/isSymbol-CPa7d4e7.js", revision: null },
        { url: "assets/kebabCase-Dn1htGYk.js", revision: null },
        { url: "assets/kvt-CPEqVXUq.js", revision: null },
        { url: "assets/kvt-K6fnWhzg.js", revision: null },
        { url: "assets/KycCustomText-CTUU_3Rq.js", revision: null },
        { url: "assets/LargeBanner-uGVpyo-O.js", revision: null },
        { url: "assets/Layout-B0JqI-qQ.js", revision: null },
        { url: "assets/Layout-Bea5cGJf.js", revision: null },
        { url: "assets/Layout-C3JSYgkQ.js", revision: null },
        { url: "assets/Layout-DsrGj888.js", revision: null },
        { url: "assets/Layout-eMDfUNmd.js", revision: null },
        { url: "assets/Layout-kwms-j1v.js", revision: null },
        { url: "assets/legacy-enums-BdcxKfbC.js", revision: null },
        { url: "assets/legacy-fonts-BbYsH4nw.js", revision: null },
        { url: "assets/LegacySettingsStyles-C_7u2B-T.js", revision: null },
        { url: "assets/Link-BO_AVVLF.js", revision: null },
        { url: "assets/LocalKycLayout-xEaLYrjm.js", revision: null },
        { url: "assets/long-names-G_UIJH0E.js", revision: null },
        { url: "assets/main-DryFSMEj.js", revision: null },
        { url: "assets/MaskedInput-CGosAaON.js", revision: null },
        { url: "assets/Menu-CbwN-UdZ.js", revision: null },
        { url: "assets/MenuItem-wDwmnSJr.js", revision: null },
        { url: "assets/MerchantRedirect-BGMo5Zym.js", revision: null },
        {
          url: "assets/MfaSmsCodeVerificationPage-BJHnSUWd.js",
          revision: null,
        },
        {
          url: "assets/mint-account-linking-status-DwXMEDoo.js",
          revision: null,
        },
        { url: "assets/MintAccount-DeutrApo.js", revision: null },
        { url: "assets/minters-Di0el6FS.js", revision: null },
        { url: "assets/minters-K6fnWhzg.js", revision: null },
        { url: "assets/mobile-validation-type-Ca0Y5gJN.js", revision: null },
        { url: "assets/mock-circulation-data-DHc3gFXy.js", revision: null },
        { url: "assets/mock-currencies-DE379c_M.js", revision: null },
        { url: "assets/mock-fiat-republic-DwpkYwB5.js", revision: null },
        { url: "assets/mock-market-Bc9e2ahr.js", revision: null },
        { url: "assets/mock-merchant-orders-CCmvN5kG.js", revision: null },
        { url: "assets/mock-merchant-summary-DDQ8OUNt.js", revision: null },
        { url: "assets/mock-supported-countries-BuLwWnky.js", revision: null },
        { url: "assets/mock-symbol-precision-xyDgCGvF.js", revision: null },
        { url: "assets/mock-symbols-XbtdsFaM.js", revision: null },
        { url: "assets/mock-transaction-history-CrqyAK3W.js", revision: null },
        { url: "assets/mock-user-DodvIz9W.js", revision: null },
        { url: "assets/mock-users-BUe8tbGi.js", revision: null },
        { url: "assets/mock-yields-distributable-XC9eMDwv.js", revision: null },
        { url: "assets/mock-yields-history-BQrmJYMo.js", revision: null },
        { url: "assets/Modals-BVw25VRj.js", revision: null },
        { url: "assets/muiSxMerge-By-TMpOR.js", revision: null },
        { url: "assets/Names-CaXmBvXg.js", revision: null },
        { url: "assets/NetworkDropdown-k4y5Zlke.js", revision: null },
        { url: "assets/OldModal-BL7OVWj-.css", revision: null },
        { url: "assets/OldModal-CTUdjHUv.js", revision: null },
        { url: "assets/OnBoardingPopUp-CbaltDgU.js", revision: null },
        { url: "assets/order-direction-B5kfqJoW.js", revision: null },
        { url: "assets/order-source-yjVi4RrL.js", revision: null },
        { url: "assets/order-type-BEH08Hfo.js", revision: null },
        { url: "assets/orders.listener-CP6LJdUF.js", revision: null },
        { url: "assets/PageContainer-Z59eRADz.js", revision: null },
        { url: "assets/Paired-DrJ9SnEm.js", revision: null },
        { url: "assets/PasswordInput-BRrGqd8k.js", revision: null },
        { url: "assets/PaybisButton-CLNx20jt.js", revision: null },
        { url: "assets/PhoneNumberInput-CtBmxYCy.js", revision: null },
        { url: "assets/pill-oEl8g0mz.js", revision: null },
        { url: "assets/pricing.listener-Btg4xjPT.js", revision: null },
        { url: "assets/ProgressBar-3p1QvBiC.js", revision: null },
        { url: "assets/ProgressBar-CjTdBJS4.js", revision: null },
        { url: "assets/RateLimitModal-ebsrfP5_.js", revision: null },
        { url: "assets/react-content-loader.es-esSY1mtT.js", revision: null },
        {
          url: "assets/react-google-recaptcha-v3.esm-DONQIyn8.js",
          revision: null,
        },
        { url: "assets/react-number-format.es-D6j4F3wj.js", revision: null },
        { url: "assets/ReceiveSection-BFnegS7B.js", revision: null },
        { url: "assets/ReceiveSection-BsFr4rUN.css", revision: null },
        { url: "assets/RecentTransactions-C169_tzK.js", revision: null },
        { url: "assets/Redemption-5ofx4yhV.js", revision: null },
        {
          url: "assets/referralNetwork.controller-BVbTSwMM.js",
          revision: null,
        },
        { url: "assets/referrers-Id6sFHAw.js", revision: null },
        { url: "assets/referrers-MIHCweLl.js", revision: null },
        { url: "assets/RequireMerchant-DhEjQ_wS.js", revision: null },
        { url: "assets/RightCTABanner-oV-nkSCk.js", revision: null },
        { url: "assets/scrollbar-CNLKTL0L.js", revision: null },
        { url: "assets/scrollbar-OSsuDtBi.css", revision: null },
        { url: "assets/SecureUpload-I1lkFr9p.js", revision: null },
        { url: "assets/SegmentedTab-Bx0ApLVn.js", revision: null },
        { url: "assets/SendSection-1oRi8x3D.css", revision: null },
        { url: "assets/SendSection-DrhrhfCo.js", revision: null },
        { url: "assets/settingsLayout-D2vPYSO0.js", revision: null },
        { url: "assets/SettingsWidget-BGE7M7dV.js", revision: null },
        { url: "assets/shared-Cn5RFyvX.js", revision: null },
        { url: "assets/shared-CWEmH2rA.js", revision: null },
        { url: "assets/shared-kyc.form-DU9uJhtw.js", revision: null },
        { url: "assets/short-names-CEnQyANM.js", revision: null },
        { url: "assets/Sign-h4o0vQnW.js", revision: null },
        { url: "assets/Skeleton-D3zW9zfH.js", revision: null },
        { url: "assets/Slider-JTzqU4Fm.js", revision: null },
        { url: "assets/slip10-C_mZIiU3.js", revision: null },
        { url: "assets/SmsCodeMfa-DpoDzOL_.js", revision: null },
        { url: "assets/SmsMfaController-DZufofn7.js", revision: null },
        { url: "assets/SmsMfaForm-tzQNy6xh.js", revision: null },
        { url: "assets/SmsNotification-jXRCWLtp.js", revision: null },
        { url: "assets/SocialIconsComponent-Df_rkOm7.js", revision: null },
        { url: "assets/socket-client-ClPHFSdE.js", revision: null },
        { url: "assets/stellar-sdk.min-BPOzoUh5.js", revision: null },
        { url: "assets/SupportText-CNbXLo8d.js", revision: null },
        { url: "assets/Switch-mECX2JQG.js", revision: null },
        { url: "assets/Tabs-nCopnh2s.js", revision: null },
        { url: "assets/TargetPrice-BEA8clvm.js", revision: null },
        { url: "assets/TermsAndConditions-BayCX0qT.js", revision: null },
        { url: "assets/TextField-DL0nOe5P.js", revision: null },
        { url: "assets/thumbnails-BgH72lVq.js", revision: null },
        { url: "assets/Tooltip-QCFsSCkk.js", revision: null },
        { url: "assets/toString-BcLWPS8a.js", revision: null },
        { url: "assets/total-C9k7lqOD.js", revision: null },
        { url: "assets/total-Dw83TXOO.js", revision: null },
        { url: "assets/TradeModal-tm71AKDs.js", revision: null },
        { url: "assets/TradingView-DLDNSOAX.js", revision: null },
        { url: "assets/translation-913JHNJM.js", revision: null },
        { url: "assets/translation-D0OQSjai.js", revision: null },
        { url: "assets/translation-D3RG5B9U.js", revision: null },
        { url: "assets/translation-Dnl1Brlj.js", revision: null },
        { url: "assets/translation-DOm1HN7m.js", revision: null },
        { url: "assets/translation-i3S5bOiW.js", revision: null },
        { url: "assets/upperFirst-DZHx3_7l.js", revision: null },
        { url: "assets/useCorporateAccounts-DAIK1YLZ.js", revision: null },
        { url: "assets/useCorporateTypes-CW5rNVMh.js", revision: null },
        { url: "assets/useFormControl-B5X7CYHM.js", revision: null },
        { url: "assets/useGaTitle-Cd3oRIF0.js", revision: null },
        { url: "assets/useIndividualAccount-B9oo-q0C.js", revision: null },
        { url: "assets/useIndustryOptions-CMVLSXkF.js", revision: null },
        { url: "assets/useOverflowFade-BK4lhouq.js", revision: null },
        { url: "assets/usePrivacyMode-sFMhOLJ_.js", revision: null },
        { url: "assets/useRequireStatus-C5948B1u.js", revision: null },
        { url: "assets/useRoundAmount-DAxUPNo0.js", revision: null },
        { url: "assets/useRoute-R5W9bIdF.js", revision: null },
        { url: "assets/useSelectedMerchantId-BYfYPQW-.js", revision: null },
        { url: "assets/useSlot-DZH0Y2jJ.js", revision: null },
        { url: "assets/useTradingView-u2vj5fwO.js", revision: null },
        { url: "assets/useValidationProfile-GhVRzjhp.js", revision: null },
        { url: "assets/util-V90YTCLf.js", revision: null },
        { url: "assets/ValidatePassphrase-BZwTJjEY.js", revision: null },
        { url: "assets/ValidateRestoration-DxXQPySM.js", revision: null },
        { url: "assets/ValidationError-DCfWViov.js", revision: null },
        { url: "assets/ValidBanks-pLLmmmje.js", revision: null },
        { url: "assets/valueTruncate-Dgq8DjOe.js", revision: null },
        { url: "assets/vault--GCLhS-V.js", revision: null },
        { url: "assets/VaultDashboard-DN6oyWFy.js", revision: null },
        { url: "assets/VaultDashboard-DOJtLOX1.css", revision: null },
        { url: "assets/VaultLayoutPage-BDEZ6HvK.css", revision: null },
        { url: "assets/VaultLayoutPage-DNzbdIOZ.js", revision: null },
        { url: "assets/VaultTransactionsPage-CDLtpV3n.js", revision: null },
        { url: "assets/velocity-CO5T3B8G.js", revision: null },
        { url: "assets/velocity-fzzY6sJt.js", revision: null },
        { url: "assets/Verification-D8KD8xPB.js", revision: null },
        { url: "assets/VerificationRequiredCard-CxytfZPs.css", revision: null },
        { url: "assets/VerificationRequiredCard-Cz5IIVmz.js", revision: null },
        { url: "assets/visitHistory-VyF4gOMN.js", revision: null },
        { url: "assets/WideTab-DPA0T2DX.js", revision: null },
        { url: "assets/withdrawal-config-2CDPaazW.js", revision: null },
        { url: "assets/WithLoaderHOC-BhoisqRA.js", revision: null },
        { url: "index.html", revision: "06ecbe1f78217a373d594ceb77adcd2a" },
        { url: "registerSW.js", revision: "1872c500de691dce40960bb85481de07" },
        {
          url: "manifest.webmanifest",
          revision: "9f88117b37e3dd72cf3799857a90ae7d",
        },
      ],
      {}
    ),
    s.cleanupOutdatedCaches(),
    s.registerRoute(
      new s.NavigationRoute(s.createHandlerBoundToURL("index.html"))
    );
});
